name: Build and release Serveragllm images

on:
  push:
    tags:
      - serveragllm-v*
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'

env:
  AWS_REGION: "us-east-1"

jobs:
  release-images:
    runs-on: ubuntu-latest
    steps:
    - name: Remove software and language runtimes we're not using
      run: |
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /opt/google/chrome
        df . -h

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch origin +refs/tags/*:refs/tags/*

    - name: Set up Docker
      uses: ./.github/actions/setup-docker
      with:
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Make and push image
      run: |
        TAG=$(git describe --tags --match "serveragllm-v*" --abbrev=0)
        ./dockers/llm.rag.service elotl/serveragllm $TAG
