apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  namespace: ${MODEL_NAMESPACE}
  labels:
    app: simple-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
    spec:
      containers:
      - name: chat
        image: elotl/llm-chat::latest
        ports:
        - containerPort: 7860
        env:
        - name: API_BASE_URL
          value: "http://serveragllm-service.${MODEL_NAMESPACE}:80"
        - name: USE_CHATBOT_HISTORY
          value: "false"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
  namespace: ${MODEL_NAMESPACE}
spec:
  selector:
    app: simple-chat
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: LoadBalancer
