apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat
  labels:
    app: simple-chat
    elotl-luna: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-chat
  template:
    metadata:
      labels:
        app: simple-chat
    spec:
      containers:
      - name: chat
        image: elotl/llm-chat:v1.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 7860
        env:
        - name: RAG_LLM_QUERY_URL
          value: "http://serveragllm-service.default.svc.cluster.local:8000"
        - name: USE_CHATBOT_HISTORY
          value: "false"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: log-storage
          mountPath: /app/logs
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: simple-chat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
spec:
  selector:
    app: simple-chat
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: ClusterIP
