apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ${MODEL_NAMESPACE}
  labels:
    app: modelsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON}
