apiVersion: batch/v1
kind: Job
metadata:
  name: createvectordb
  namespace: ${MODEL_NAMESPACE}
  labels:
    app: modeldataingest
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: createvectordb
        image: elotl/createvectordb:v1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1.5"
            memory: "1G"
        env:
          - name: AWS_ACCESS_KEY_ID
            value: ${AWS_ACCESS_KEY_ID}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${AWS_SECRET_ACCESS_KEY}
          - name: VECTOR_DB_S3_FILE
            value: ${VECTOR_DB_S3_FILE}
          - name: VECTOR_DB_INPUT_TYPE
            value: ${VECTOR_DB_INPUT_TYPE}
          - name: VECTOR_DB_INPUT_ARG
            value: ${VECTOR_DB_INPUT_ARG}
      imagePullSecrets:
      - name: regcred
