apiVersion: batch/v1
kind: Job
metadata:
  name: createvectordb
  labels:
    app: modeldataingest
    elotl-luna: "true"
  annotations:
    node.elotl.co/instance-type-regexp: "^(t3.xlarge|n2-standard-4)$"
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: createvectordb
        image: elotl/createvectordb:v1.2.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1.5"
            memory: "1G"
        env:
          - name: AWS_ACCESS_KEY_ID
            value: ${AWS_ACCESS_KEY_ID}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${AWS_SECRET_ACCESS_KEY}
          - name: VECTOR_DB_INPUT_TYPE
            value: ${VECTOR_DB_INPUT_TYPE}
          - name: VECTOR_DB_INPUT_ARG
            value: ${VECTOR_DB_INPUT_ARG}
          - name: VECTOR_DB_S3_BUCKET
            value: ${VECTOR_DB_S3_BUCKET}
          - name: VECTOR_DB_S3_FILE
            value: ${VECTOR_DB_S3_FILE}
          - name: EMBEDDING_CHUNK_SIZE
            value: ${EMBEDDING_CHUNK_SIZE}
          - name: EMBEDDING_CHUNK_OVERLAP
            value: ${EMBEDDING_CHUNK_OVERLAP}
          - name: EMBEDDING_MODEL_NAME
            value: ${EMBEDDING_MODEL_NAME}
