name: "Set Up Docker"
description: "Set up Docker"

inputs:
  docker-username:
    description: "DockerHub username"
    required: true
  docker-password:
    description: "DockerHub password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
