apiVersion: v1
kind: PersistentVolume
metadata:
  name: rag-llm-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/rag-llm-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-llm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
