apiVersion: v1
kind: PersistentVolume
metadata:
  name: questionanswerdb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/zendesk.db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: questionanswerdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
