apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveragllm-deployment
  namespace: ${MODEL_NAMESPACE}
  labels:
    app: modelragllmserve
spec:
  replicas: 1
  selector:
    matchLabels:
      model: serveragllm
  template:
    metadata:
      labels:
        model: serveragllm
    spec:
      containers:
        - name: serveragllm
          image: elotl/serveragllm:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1.5"
              memory: "1G"
          env:
          - name: AWS_ACCESS_KEY_ID
            value: ${AWS_ACCESS_KEY_ID}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${AWS_SECRET_ACCESS_KEY}
          - name: VECTOR_DB_S3_FILE
            value: ${VECTOR_DB_S3_FILE}
          - name: MODEL_LLM_SERVER_URL
            value: ${MODEL_LLM_SERVER_URL}
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: serveragllm-service
  namespace: ${MODEL_NAMESPACE}
  labels:
    app: modelragllmserve
spec:
  type: LoadBalancer
  selector:
    model: serveragllm
  ports:
    - name: http
      port: 80
      targetPort: 8000
